spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tome
    username: dgsw05
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ...
            client-secret: ...
            scope:
              - email
              - profile
jwt:
  issuer: kmk541124@gmail.com
  secret_key: tome-server
