spring:
  application:
    name: tome

  datasource:
    url: jdbc:postgresql://localhost:5432/tome
    username: postgres
    password: Tortoise0109@@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true